#!/bin/sh

version=`grep "AppConfig.version =" lib/Tj3Config.rb | sed "s/.*'\(.*\)'/\1/g"`
gem=pkg/TaskJuggler-${version}.gem

echo "Generating User Manual..."
mkdir -p data/manual
rm data/manual/*.html
cd lib ; ruby UserManual.rb ; cd ..
rake rdoc || exit 1
rake gem || exit 1


