#! /bin/bash

function cleanup
{
  /bin/rm -rf timesheets.log acceptable_intervals \
              TimeSheets TimeSheetTemplates \
	      sender.log receiver.log
  killall -9 tj3 2> /dev/null
} 

cleanup
tj3 -s project.tjp &
# Wait some time so tj3 can go into server mode.
sleep 5 

# Run a sender test.
tj3ts_sender --dryrun -e 2002-03-01 > sender.log
# Run a receiver test
tj3ts_receiver --dryrun < dev2_mail1 >> receiver.log || exit 1
tj3ts_receiver --dryrun < dev2_mail2 >> receiver.log || exit 1

if test `fgrep ERROR timesheets.log | wc -l` != 0 ; then
  echo "ERROR: Something went wrong!"
  exit 1
fi  
if test `fgrep WARN timesheets.log | wc -l` != 1 ; then
  echo "ERROR: Warnings don't match!"
  exit 1
fi  
if test `fgrep INFO timesheets.log | wc -l` != 29 ; then
  echo "ERROR: Info messages don't match!"
  exit 1
fi  
if test `fgrep 'Your weekly report template' timesheets.log | wc -l` != 6 ; then
  echo "ERROR: Wrong number of emails send out!"
  exit 1
fi  

cleanup
exit 0
