#! /bin/bash

function cleanup
{
  /bin/rm -rf timesheets.log acceptable_intervals \
              TimeSheets TimeSheetTemplates \
	      sender.log receiver.log
  killall -9 tj3
}

cleanup
tj3 -s project.tjp &
# Wait some time so tj3 can go into server mode.
sleep 5 

# Run a sender test.
tj3ts_sender --nomail -e 2002-03-01 > sender.log
# Run a receiver test
tj3ts_receiver --nomail < dev2_mail > receiver.log

if test `fgrep ERROR timesheets.log | wc -l` != 0 ; then
  echo "ERROR: Something went wrong!"
  exit 1
fi  
if test `fgrep WARN timesheets.log | wc -l` != 1 ; then
  echo "ERROR: Warnings don't match!"
  exit 1
fi  

cleanup
exit 0
