#! /bin/bash

function cleanup
{
  /bin/rm -rf statussheets.log \
              StatusSheets StatusSheetTemplates \
	      sender.log receiver.log
  killall -9 tj3 2> /dev/null
}

function error
{
  echo "ERROR: $1"
  exit 1
}

function check
{
  count=`grep "$1" "$2" | wc -l`	
  if test $count != $3 ; then
    error "$2 contains ${count} times \"${1}\" instead of $3 times!"
  fi  
}

cleanup
tj3 -s project.tjp &
# Wait some time so tj3 can go into server mode.
sleep 5 

# Run a sender test.
tj3ss_sender --dryrun -e 2002-03-02 > sender.log || error "sender1"
check "From: foo@bar.com" sender.log 2
check "Content-Disposition: attachment;" sender.log 2
check "^statussheet " sender.log 2

# Run a receiver test
tj3ss_receiver --dryrun < boss_mail >> receiver.log || error "rec1"
tj3ss_receiver --dryrun < dev2_mail >> receiver.log || error "rec2"
check "From: foo@bar.com" receiver.log 2
check "Report from " receiver.log 3
check "\[Yellow\]" receiver.log 1
check "\[Green\]" receiver.log 2

check ERROR statussheets.log 0
check WARN statussheets.log 1
check INFO statussheets.log 27
check "Your weekly report template" statussheets.log 2

cleanup
exit 0
